sudo: false
language: python
matrix:
  - os: osx
    language: generic
  - python: pypy
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9-dev
install:
  - scripts/install-on-travis.sh
script:
  - scripts/run-on-travis.sh make check
  - scripts/run-on-travis.sh make test
after_success:
  - scripts/run-on-travis.sh coveralls
branches:
  except:
    - /^[0-9]/
